### ISSUE TITLE
[resolver] (0.25.0-alpha.2) DnsSec validate enabled should also use ProtoErrorKind::NoRecordsFound and skip validation

### ISSUE THREAD

**Issue by kolbma** [hickory-dns/hickory-dns#2503]
When looking up different types where no RR exists, there should be used `ProtoErrorKind::NoRecordsFound`.  
This is the case if `ResolverOpts::validate == false`.

But if `ResolverOpts::validate == true` there is currently `ProtoErrorKind::Message` with _"could not validate negative response missing SOA"_.  
Why it tries to validate anything if there is no existing RR to validate?

So e.g. if you want to lookup NS for a not existing domain, you get error "could not validate negative response missing SOA".  
Does this make any sense?

**Comment by marcus0x62** [comment]
This overall problem is complicated, and something I'm working on in #2502, but the short answer is we can't just skip validation because of a missing record in a zone. If Hickory is configured as a validating name server and the parent zone for a given query has DS records for the sub zone being queried, then things like missing SOA records in the sub zone will (and should) trigger validation failures for some queries.

There is a bug where SOA (and associated DNSSEC records) are not being propagated correctly during error type conversion, which is more than likely what you are seeing -  Hickory probably is getting an SOA record for the query you are attempting, but we aren't passing it correctly through the entire resolution process. We'd need a packet capture (or debug logs) to be sure.

**Comment by kolbma** [comment]
Well, I've tested it with an unregistered domain/NXDOMAIN. And then you get this crude _"could not validate negative response missing SOA"_ error.  
The SOA is from the NIC. And the RRs of the NIC are validatable secure.  
But I mean, what should be validated for the unregistered domain? 

_delv_ returns with
```
;; resolution failed: ncache nxdomain
; negative response, fully validated
```

**Comment by marcus0x62** [comment]
In the case of a query against an unregistered domain with a parent zone that is signed and Hickory as a validating recursor, the process should go, approximately, like this:

* Hickory receives a query for 'unregistered.com'
* Hickory looks up the com nameservers based on the configured roots.
* Hickory asks for the nameservers for unregistered.com from the com nameservers.
* Com nameservers return NXDomain with the SOA for com. and several NSEC/NSEC3 and RRSIG records to prove unregistered.com does not exist.
* Hickory validates the returned records. against the dnskeys for com.
* Hickory requests the DS records for com from the root servers and verifies those match the dnskey from the previous request
* Hickory verifies the root servers keys against the trust anchor.

More generally, for any negative response as a validating resolver, we need to validate either that the non-existence proofs we have are valid, or that the lack of non-existence proofs is valid before returning a response to the client.  We can't skip validation in these scenarios.

**Comment by marcus0x62** [comment]
@kolbma this should be fixed now. Can you retest and let me know if this is working for you now?

**Comment by kolbma** [comment]
Sorry, but I can't check this out at the moment. In alpha.3 there are now too many API incompatibilities (Generics and Async) to before, that it makes no sense to fiddle in support of 0.24 and 0.25 in my code base with feature cfg.

**Comment by marcus0x62** [comment]
Thanks @kolbma. I'm going to close this out for now; feel free to reopen it if you run into this problem in the future.
